.TH 90s 1 90s\-VERSION
.SH NAME
90s \- the 90s shell
.SH SYNOPSIS
.B 90s
.SH DESCRIPTION
90s is a shell that is heavily customized, minimalistic, simple but with several features. That includes simple syntax highlighting for showing validity of commands with history search and support of environment varaibles.
.SH AUTHOR
Made by Night Kaly
.B <night@night0721.xyz>
