.TH rush 1 rush\-VERSION
.SH NAME
rush \- the rush shell
.SH SYNOPSIS
.B rush
.SH DESCRIPTION
rush is a shell that is heavily customized, minimalistic, simple but with several features. That includes simple syntax highlighting for showing validity of commands with history search and support of environment varaibles.
.SH AUTHOR
Made by Night Kaly
.B <night@night0721.xyz>
